"""Typed project, task, and failure states.

Contract Sections 6.2, 9.3, 10.6, 10.7, 19.2. These are closed enumerations: a
state that is not here is not a state the harness may report. That is the point
-- Section 6.2 exists so a run cannot end in an ambiguous "mostly done".
"""

from __future__ import annotations

from enum import StrEnum


class ProjectState(StrEnum):
    """Contract Section 6.2. Only these end a run."""

    VERIFIED_COMPLETE = "VERIFIED_COMPLETE"
    BLOCKED_OWNER_DECISION = "BLOCKED_OWNER_DECISION"
    BLOCKED_EXTERNAL_ACCESS = "BLOCKED_EXTERNAL_ACCESS"
    FAILED_CONTRACT = "FAILED_CONTRACT"
    FAILED_ASSURANCE = "FAILED_ASSURANCE"
    FAILED_INFRASTRUCTURE = "FAILED_INFRASTRUCTURE"
    CANCELED = "CANCELED"

    # Explicitly NOT terminal, kept here so the projection cannot invent them.
    RUNNING = "RUNNING"


TERMINAL_PROJECT_STATES = frozenset(
    {
        ProjectState.VERIFIED_COMPLETE,
        ProjectState.BLOCKED_OWNER_DECISION,
        ProjectState.BLOCKED_EXTERNAL_ACCESS,
        ProjectState.FAILED_CONTRACT,
        ProjectState.FAILED_ASSURANCE,
        ProjectState.FAILED_INFRASTRUCTURE,
        ProjectState.CANCELED,
    }
)


class TaskState(StrEnum):
    """Contract Section 9.3."""

    PROPOSED = "PROPOSED"
    READY = "READY"
    CLAIMED = "CLAIMED"
    RUNNING = "RUNNING"
    CANDIDATE_COMPLETE = "CANDIDATE_COMPLETE"
    VERIFYING = "VERIFYING"
    PASSED = "PASSED"
    MERGED = "MERGED"
    CLOSED = "CLOSED"

    BLOCKED_DEPENDENCY = "BLOCKED_DEPENDENCY"
    BLOCKED_OWNER_DECISION = "BLOCKED_OWNER_DECISION"
    BLOCKED_EXTERNAL_ACCESS = "BLOCKED_EXTERNAL_ACCESS"
    FAILED_IMPLEMENTATION = "FAILED_IMPLEMENTATION"
    FAILED_WIRING = "FAILED_WIRING"
    FAILED_VISIBLE_TEST = "FAILED_VISIBLE_TEST"
    FAILED_HOLDOUT = "FAILED_HOLDOUT"
    FAILED_MUTATION = "FAILED_MUTATION"
    FAILED_ORACLE = "FAILED_ORACLE"
    FAILED_SCOPE = "FAILED_SCOPE"
    FAILED_PROVENANCE = "FAILED_PROVENANCE"
    STALE_ASSIGNMENT = "STALE_ASSIGNMENT"
    REWORK_REQUIRED = "REWORK_REQUIRED"
    QUARANTINED = "QUARANTINED"
    CANCELED = "CANCELED"


#: Contract Section 9.3: "Workers may submit CANDIDATE_COMPLETE. Only gates may
#: produce PASSED." Enforced by the ledger, not by convention.
WORKER_SUBMITTABLE_STATES = frozenset(
    {TaskState.CANDIDATE_COMPLETE, TaskState.REWORK_REQUIRED, TaskState.BLOCKED_DEPENDENCY}
)
GATE_ONLY_STATES = frozenset({TaskState.PASSED, TaskState.MERGED})


class FailureClass(StrEnum):
    """Contract Section 10.6. Classify before retrying."""

    TRANSIENT_PROVIDER_FAILURE = "TRANSIENT_PROVIDER_FAILURE"
    RATE_LIMIT = "RATE_LIMIT"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    WORKER_CONTEXT_LIMIT = "WORKER_CONTEXT_LIMIT"
    TOOL_FAILURE = "TOOL_FAILURE"
    TEST_FAILURE = "TEST_FAILURE"
    WIRING_FAILURE = "WIRING_FAILURE"
    CONTRACT_DRIFT = "CONTRACT_DRIFT"
    HOLDOUT_FAILURE = "HOLDOUT_FAILURE"
    ORACLE_INVALID = "ORACLE_INVALID"
    PROTECTED_ACCESS = "PROTECTED_ACCESS"
    INFRASTRUCTURE_FAILURE = "INFRASTRUCTURE_FAILURE"


class OwnerInterrupt(StrEnum):
    """Contract Section 10.7. This list is CLOSED.

    ``autonomy-policy.yaml`` is explicit: anything else asking for permission is
    drift. Routine implementation, retry, fallback, test repair, PR creation and
    green auto-merge must never produce an interrupt.
    """

    OWNER_SCOPE_DECISION = "OWNER_SCOPE_DECISION"
    OWNER_PRIORITY_DECISION = "OWNER_PRIORITY_DECISION"
    OWNER_RISK_ACCEPTANCE = "OWNER_RISK_ACCEPTANCE"
    MISSING_REQUIRED_CREDENTIAL = "MISSING_REQUIRED_CREDENTIAL"
    IRREVERSIBLE_EXTERNAL_ACTION = "IRREVERSIBLE_EXTERNAL_ACTION"
    CONTRACT_AMENDMENT_REQUIRED = "CONTRACT_AMENDMENT_REQUIRED"
    IRRESOLVABLE_EVIDENCE_CONFLICT = "IRRESOLVABLE_EVIDENCE_CONFLICT"


class DriftFinding(StrEnum):
    """Contract Section 19.2."""

    UNLINKED_TASK = "UNLINKED_TASK"
    UNAPPROVED_SCOPE_EXPANSION = "UNAPPROVED_SCOPE_EXPANSION"
    REQUIREMENT_WEAKENING = "REQUIREMENT_WEAKENING"
    REDEFINED_SUCCESS = "REDEFINED_SUCCESS"
    OUTSIDE_ALLOWED_PATHS = "OUTSIDE_ALLOWED_PATHS"
    STALE_CONTRACT_VERSION = "STALE_CONTRACT_VERSION"
    STALE_INPUT_ARTIFACT = "STALE_INPUT_ARTIFACT"
    DUPLICATE_OR_CONFLICTING_WORK = "DUPLICATE_OR_CONFLICTING_WORK"
    ROLE_CONFLICT = "ROLE_CONFLICT"
    PROTECTED_ASSET_ACCESS = "PROTECTED_ASSET_ACCESS"
    MISSING_WIRING = "MISSING_WIRING"
    UNSUPPORTED_REIMPLEMENTATION = "UNSUPPORTED_REIMPLEMENTATION"
    OUT_OF_SCOPE_SECURITY_EXPANSION = "OUT_OF_SCOPE_SECURITY_EXPANSION"
    OUT_OF_SCOPE_OBSERVATION = "OUT_OF_SCOPE_OBSERVATION"


class ContractReviewOutcome(StrEnum):
    """Contract Section 19.4. Only CONTRACT_REAFFIRMED advances automatically."""

    CONTRACT_REAFFIRMED = "CONTRACT_REAFFIRMED"
    DRIFT_DETECTED = "DRIFT_DETECTED"
    EVIDENCE_STALE = "EVIDENCE_STALE"
    RISK_CHANGED = "RISK_CHANGED"
    CONTRACT_AMBIGUITY = "CONTRACT_AMBIGUITY"
    AMENDMENT_REQUIRED = "AMENDMENT_REQUIRED"


class Verdict(StrEnum):
    """The only verdict values the protected verifier may return (Section 17.2)."""

    PASS = "PASS"
    FAIL = "FAIL"
    UNVERIFIABLE = "UNVERIFIABLE"
